-- a script that creates a database and a table with autogenerated,unique,not null and primary key id
-- does not fail if they already exist
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS states (
	id INT AUTO_INCREMENT PRIMARY KEY UNIQUE NOT NULL,
	name VARCHAR(256) NOT NULL
);
